name: Build and Publish Compiler Plugin

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build
      run: |
        ./gradlew build

    - name: Publish to Maven Central
      env:
        MAVEN_URL: ${{ secrets.MAVEN_URL }}
        MAVEN_USER: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASS: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      run: |
        ./gradlew publish
